### ISSUE TITLE
Bug on tap action

### ISSUE THREAD

**Issue by Josuepdc** [loregr/LGButton#50]
After updating from 1.0.5 to 1.1.1, I need to hold the button to receive the IBAction in my view controller instead of just tap the button. I tested some things and found that if you remove the "if" of line 708 of file "LGButton.swift" (based on commit 3dfd991b3c823465b44a7e22fe914694382d0303), the problem will no longer exists.

**Comment by loregr** [comment]
@Josuepdc could you please provide more info on your local setup and view/gestures hierarchy? The issue doesn't seem to occur on the example project. Also, your suggestion may fix your problem but won't work if the button is inside a view with a `UITapGestureRecognizer` attached. Also please check the latest version of the pod that includes @l3bel fixes, it "may" be in some way related to your issue. Thanks.

**Comment by landa** [comment]
I have the same problem. You need to hold the button for it to publish a 'tap up' event.

**Comment by loregr** [comment]
@landa could you please provide more info on your local setup and view/gestures hierarchy? The issue doesn't seem to occur on the example project. Thanks.

**Comment by landa** [comment]
Yes. I actually switched the pod to use @Josuepdc's fork, and it works well.

My buttons live within an MDCCard, which is in a UITableViewController subclass within a ContainerView.

**Comment by l3bel** [comment]
@loregr any particular reason why you are not calling super at the beginning of touchesBegan, touchesEnded, etc? not sure but this might also fix the issue.
@landa can you test this (switch back to the "normal" version, add calls to super at the beginning of the overridden touchesBla.. funcs) and see what gives, because with @Josuepdc's fork it is not possible to "cancel" the tap if touches end outside the button, which is why @loregr added the test in the first place (Lorenzo please correct me if I am wrong on this)

**Comment by landa** [comment]
@l3bel what exactly should I do? I'm not overriding a function, so there's no super to call. I'm just using a touch up inside IBAction.

**Comment by l3bel** [comment]
@landa sorry I mean to add the calls inside LGButton.swift (from the original repository, not @Josuepdc's fork)

**Comment by l3bel** [comment]
@landa 
....
`
    
    override open func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?){
		super.touchesBegan(touches, with: event)
        pressed = true
    }
    
    override open func touchesEnded(_ touches: Set<UITouch>, with event: UIEvent?){
		super.touchesEnded(touches, with: event)
        let shouldSendActions = pressed
        pressed = false
        if shouldSendActions{
            sendActions(for: .touchUpInside)
        }
    }
    
    override open func touchesMoved(_ touches: Set<UITouch>, with event: UIEvent?){
		super.touchesMoved(touches, with: event)
        if let touchLoc = touches.first?.location(in: self){
            if (touchLoc.x < -touchDisableRadius ||
                touchLoc.y < -touchDisableRadius ||
                touchLoc.x > self.bounds.size.width + touchDisableRadius ||
                touchLoc.y > self.bounds.size.height + touchDisableRadius){
                pressed = false
            }
            else if self.touchAlpha == .untouched {
                pressed = true
            }
        }
    }
    
    override open func touchesCancelled(_ touches: Set<UITouch>, with event: UIEvent?) {
		super.touchesCancelled(touches, with: event)
        pressed = false
    }

`
....
Also please be aware of "bug" #56 in version 1.1.4 (FontAwesome.ttf file needs to be copied from the root of the repository to the Resources folder. Waiting for @loregr to fix)

**Comment by jmoscatiello** [comment]
Experiencing the same thing but @Josuepdc 's branch fixed it

**Comment by l3bel** [comment]
@jmoscatiello @landa without the if test in place (removed in @Josuepdc 's branch) it is not possible to "cancel" a tap (by means of lifting finger outside of the control). Have you tried what @loregr and myself suggest above (using version 1.1.3 and/or adding calls to super.touches... )?

**Comment by jmoscatiello** [comment]
I tried it out. Seems to work! Thanks guys

**Comment by l3bel** [comment]
@jmoscatiello thanks for your reply, glad it worked. Did 1.1.3 work "as is" or did you have to add the calls to super.touchesBla?

**Comment by jmoscatiello** [comment]
I had to add to the calls. Not a big deal.

**Comment by l3bel** [comment]
Perfect! Thank you very much for your feedback! If time permits and @landa and @Josuepdc confirm adding the calls to super works for them too, I will make a pull request for when @loregr is back ;)

**Comment by loregr** [comment]
Hi all, sorry for the late response but I've been away for the weekend with no access to my laptop. Anyway thanks @l3bel for having followed the discussion and for having provided great suggestions. I'm still not able to replicate the issue, but I've just released [v1.1.5](https://github.com/loregr/LGButton/releases/tag/1.1.5) where I've implemented some improvements based on the discussion above. @jmoscatiello or whoever else was getting the issue, could you please check if it is now fixed in the latest release? Thanks 🌟

**Comment by loregr** [comment]
I'm closing this issue since I'm pretty confident it has been fixed with the latest release. If that's not the case feel free to re-open it.

**Comment by c0state** [comment]
Didn't get to look into it yet, but I still see this in 1.1.5

**Comment by rachelrobynslater** [comment]
I'm also still seeing this issue. 
I'm using an IBAction (touch up inside, although I've tested other variations). 
As @landa said, you need to hold the button down for ~2 seconds for it to register. I simple click doesn't work.

**Comment by jmoscatiello** [comment]
@rachelrobynslater just connect touch up inside to the method to connect the click, by default it wont work.
